# DATA PRE-PROCESSING

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("./Datasets/LT.csv")
x = dataset.iloc[1:, 1:5].values
y = dataset.iloc[1:, -1].values

In [3]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, :-1])
x[:, :-1] = imputer.transform(x[:, :-1])

In [4]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2)

# LINEAR REGRESSION MULTIVARIABLE


In [5]:
from sklearn.linear_model import LinearRegression
lr_m =  LinearRegression()
lr_m.fit(xtrain,ytrain)
lr_m_pred = lr_m.predict(xtest)

In [6]:
np.set_printoptions(precision=2)
print(np.concatenate((ytest.reshape(len(ytest),1), lr_m.predict(xtest).reshape(len(lr_m.predict(xtest)),1)),1))

[[1609.8  1623.25]
 [1660.15 1640.53]
 [1283.25 1277.77]
 ...
 [1971.45 2002.14]
 [2473.25 2515.58]
 [1282.4  1284.45]]


# LINEAR REGRESSION SINGLE VARIABLE

In [7]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(xtrain[:,0].reshape(-1,1), ytrain)

LinearRegression()

In [8]:
lr_pred = lr.predict(xtest[:,0].reshape(-1,1))
print(np.concatenate((ytest.reshape(-1,1), lr_pred.reshape(-1,1)),-1))

[[1609.8  1671.97]
 [1660.15 1555.5 ]
 [1283.25 1287.24]
 ...
 [1971.45 2021.93]
 [2473.25 2444.52]
 [1282.4  1298.68]]


# POLYNOMIAL LINEAR REGRESSION

In [33]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 1)
X_poly = poly.fit_transform(x) 
lin2 = LinearRegression()

In [34]:
plrxtrain, plrxtest, plrytrain, plrytest = train_test_split(X_poly,y,test_size=0.2)

In [35]:
lin2.fit(plrxtrain, plrytrain)

LinearRegression()

In [36]:
plr_pred = lin2.predict(plrxtest)
print(np.concatenate((plrytest.reshape(-1,1), plr_pred.reshape(-1,1)),-1))

[[1543.9  1538.65]
 [ 845.    847.81]
 [1374.65 1372.23]
 ...
 [1500.65 1497.66]
 [ 939.55  951.17]
 [ 768.9   774.32]]


# SUPPORT VECTOR REGRESSION

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [10]:
temp = scaler.fit_transform(x)

In [11]:
svrxtrain, svrxtest, svrytrain, svrytest = train_test_split(temp,y,test_size=0.2)

In [12]:
from sklearn.svm import SVR
clf_svr= SVR(kernel="rbf", C=100, gamma="auto")
clf_svr.fit(svrxtrain,svrytrain)

SVR(C=100, gamma='auto')

In [13]:
svr_pred = clf_svr.predict(svrxtest)
print(np.concatenate((svrytest.reshape(-1,1), svr_pred.reshape(-1,1)),-1))

[[ 853.25  845.05]
 [1642.75 1631.72]
 [1218.9  1215.8 ]
 ...
 [1511.1  1514.75]
 [1629.   1611.86]
 [1383.25 1389.64]]


# DECISION TREE REGRESSION

# RANDOM FOREST REGRESSION

In [14]:
from sklearn.ensemble import RandomForestRegressor
rand_reg = RandomForestRegressor(n_estimators=10)
rand_reg.fit(xtrain, ytrain)
rand_pred = rand_reg.predict(xtest)

# Comparing Model R2 score

Linear Regression Multivariable

Linear Regression Simple

Linear Regression Polynomial

Support Vector Regression

Decision Tree Regression

Random Forest Regression

# Results