# DATA PRE-PROCESSING

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv("/content/LT.csv")
x = dataset.iloc[1:, 1:5].values
y = dataset.iloc[1:, -1].values

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, :-1])
x[:, :-1] = imputer.transform(x[:, :-1])

In [7]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2)

# LINEAR REGRESSION MULTIVARIABLE


In [8]:
from sklearn.linear_model import LinearRegression
lr_m =  LinearRegression()
lr_m.fit(xtrain,ytrain)
lr_m_pred = lr_m.predict(xtest)

In [9]:
np.set_printoptions(precision=2)
print(np.concatenate((ytest.reshape(len(ytest),1), lr_m.predict(xtest).reshape(len(lr_m.predict(xtest)),1)),1))

[[2428.7  2393.79]
 [1131.7  1129.49]
 [1314.3  1309.8 ]
 ...
 [1387.4  1379.07]
 [2902.   2909.11]
 [1327.15 1327.89]]


# LINEAR REGRESSION SINGLE VARIABLE

In [10]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(xtrain[:,0].reshape(-1,1), ytrain)

LinearRegression()

In [11]:
lr_pred = lr.predict(xtest[:,0].reshape(-1,1))
print(np.concatenate((ytest.reshape(-1,1), lr_pred.reshape(-1,1)),-1))

[[2428.7  2446.46]
 [1131.7  1125.41]
 [1314.3  1295.07]
 ...
 [1387.4  1362.57]
 [2902.   2898.15]
 [1327.15 1291.04]]


# POLYNOMIAL LINEAR REGRESSION

# SUPPORT VECTOR REGRESSION

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [13]:
temp = scaler.fit_transform(x)

In [14]:
svrxtrain, svrxtest, svrytrain, svrytest = train_test_split(temp,y,test_size=0.2)

In [15]:
from sklearn.svm import SVR
clf_svr= SVR(kernel="rbf", C=100, gamma="auto")
clf_svr.fit(svrxtrain,svrytrain)

SVR(C=100, gamma='auto')

In [16]:
svr_pred = clf_svr.predict(svrxtest)
print(np.concatenate((svrytest.reshape(-1,1), svr_pred.reshape(-1,1)),-1))

[[1551.4  1550.21]
 [1309.   1303.25]
 [1437.85 1442.61]
 ...
 [ 656.4   680.54]
 [ 825.55  827.16]
 [1688.   1672.62]]


# DECISION TREE REGRESSION

In [28]:
from sklearn.tree import DecisionTreeRegressor 
  
regressor = DecisionTreeRegressor(random_state = 0) 

regressor.fit(xtrain, ytrain)

DecisionTreeRegressor(random_state=0)

In [29]:
ypred = regressor.predict(xtest)

In [30]:
from sklearn import metrics
print('r2 value:',metrics.r2_score(ytest, ypred))

r2 value: 0.9981096450066252


In [31]:
print('accuracy',100- (np.mean(np.abs((ytest - ypred) / ytest)) * 100))

accuracy 99.10794333962592


# RANDOM FOREST REGRESSION

In [18]:
from sklearn.ensemble import RandomForestRegressor
rand_reg = RandomForestRegressor(n_estimators=10)
rand_reg.fit(xtrain, ytrain)
rand_pred = rand_reg.predict(xtest)

# Comparing Model R2 score

Linear Regression Multivariable

Linear Regression Simple

Linear Regression Polynomial

Support Vector Regression

Decision Tree Regression

Random Forest Regression

# Results